Qiskit/qiskit-app-benchmarks

.github/actions/install-applications/action.yml, .github/actions/install-libraries/action.yml, .github/actions/install-main-dependencies/action.yml, .github/workflows/main.yml, .pylintdict, Makefile, README.md, machine_learning/Makefile, nature/Makefile, optimization/Makefile, optimization/benchmarks/maxcut.py
=> Enable github actions

README.md, finance/Makefile, machine_learning/Makefile, nature/Makefile, optimization/Makefile
=> Fix typos in readme

.github/CODEOWNERS, .github/workflows/main.yml, Makefile, README.md, finance/Makefile, machine_learning/Makefile, nature/Makefile, optimization/Makefile
=> Update codeowners, add commands to makefile

.github/workflows/main.yml, finance/asv.conf.json, machine_learning/asv.conf.json, nature/asv.conf.json, optimization/asv.conf.json
=> Improve configurations settings

.github/workflows/main.yml, .pylintdict, .pylintrc, CODE_OF_CONDUCT.md, Makefile, requirements-dev.txt, tools/verify_headers.py
Equivalent to Qiskit/qiskit-machine-learning#133
=> Move away from using pylint header plugin

finance/asv.conf.json, machine_learning/asv.conf.json, nature/asv.conf.json, optimization/asv.conf.json, tools/cron_script.sh
=> Change script to give exec permission to github ask password

.github/actions/install-libraries/action.yml, .github/workflows/main.yml
=> CI: run asv --quick

.github/workflows/main.yml
=> Add concurrency to CI

docs/conf.py, tools/cron_script.sh
=> Fix cron asv path and sphinx conf

tools/cron_script.sh
`asv NEW` returns non zero if there are no new commits to benchmark. Changed the script to check it.
=> Check asv command return code

machine_learning/benchmarks/circuit_qnn_classifier_benchmark.py, machine_learning/benchmarks/circuit_qnn_classifier_fit_benchmark.py, tools/check_copyright.py, tools/verify_headers.py
=> Fix lint f-string errors

tools/cron_script.sh
Since ML benchmarks take the longest to run, moving to bottom so the other domains can push their results first.
=> Run ML benchmarks last

CONTRIBUTING.md, Makefile, machine_learning/benchmarks/base_classifier_benchmark.py, machine_learning/benchmarks/circuit_qnn_classifier_benchmark.py, machine_learning/benchmarks/circuit_qnn_classifier_fit_benchmark.py, machine_learning/benchmarks/opflow_qnn_classifier_benchmark.py, machine_learning/benchmarks/opflow_qnn_classifier_fit_benchmark.py, machine_learning/benchmarks/vqc_benchmark.py, machine_learning/benchmarks/vqc_fit_benchmark.py, nature/benchmarks/protein_folding_problem_benchmark.py, optimization/benchmarks/maxcut.py, tools/check_version.py
=> Add version property to benchmarks and check for it in the CI

optimization/benchmarks/knapsack.py
I add the knapsack problem for benchmarking, I used the same syntaxis of the Maxcut problem.
=> Adding knapsack problem for benchmarking

.github/workflows/main.yml, Makefile, docs/conf.py, docs/lowercase_filter.py, mypy.ini, pyproject.toml, requirements-dev.txt, tools/check_version.py
=> Bump black version and add some mypy options

Makefile, requirements-dev.txt, tools/check_version.py
=> Bump black version and relax constraint

.pylintdict, requirements-dev.txt, tools/benchmarks.sh, tools/cron_script.sh, tools/ml_unittests.sh, tools/send_notification.py
=> Add Machine Learning GPU Unit Tests Phase

tools/cron_script.sh, tools/ml_unittests.sh, tools/send_notification.py
=> Add rust location to PATH inside cron script

tools/cron_script.sh
Set the CARGO_HOME inside cron script until crontab is modified.
=> Set CARGO_HOME inside cron script

requirements-dev.txt, tools/benchmarks.sh, tools/cron_script.sh, tools/ml_unittests.sh
=> Create python env. in cron script

tools/benchmarks.sh, tools/cron_script.sh, tools/ml_unittests.sh
=> Post benchmarks logs to slack

tools/benchmarks.sh, tools/cron_script.sh, tools/main_script.sh, tools/ml_unittests.sh
=> Create main script

requirements-dev.txt
=> Add virtualenv to requirements

.github/workflows/main.yml, tools/benchmarks.sh
=> Run asv update in order to update results to new format

.github/workflows/main.yml, docs/Makefile, tools/benchmarks.sh, tools/install_rust.sh, tools/main_script.sh
=> Set sphinx-build --keep-going by default

.github/actions/install-main-dependencies/action.yml, .github/workflows/main.yml, machine_learning/benchmarks/opflow_qnn_regressor_fit_benchmark.py, tools/check_version.py
=> Cache Terra/Aer in CI

.github/actions/install-main-dependencies/action.yml, docs/conf.py
=> Fix sphinx config language

requirements-dev.txt
=> Pin pylint to < 2.14.0

nature/benchmarks/protein_folding_problem_benchmark.py
During benchmark methods discovery, `asv` will instantiate the benchmark class. Any code inside `__init__` will run unnecessarily adding to the overall `asv` run even if it doesn't affect the benchmark results.
Changing to lazy objects instantiation. 
Even though in this case it isn't costly as the objects inside the old `__init__` are small, it shows a way of avoiding doing any process during class creation.
=> Avoid object creation inside Nature benchmark class  __init__ method

tools/ml_unittests.sh
=> Use nvidia cuda on ML GPU unit tests

tools/main_script.sh
Create python env. using python3.8 in cron script
=> Cron create python env. using python 3.8

.github/actions/install-main-dependencies/action.yml
=> Fix CI errors

.github/workflows/main.yml
Following advice from Github, update actions to latest versions
=> Update Github Actions versions

.pylintrc, nature/benchmarks/linear_mapper_benchmark.py
=> Change from retworkx to rustworkx

.github/actions/install-main-dependencies/action.yml
Github actions updated Ubuntu-latest OS so it needed a change in the Aer build
=> Fix CI aer build

requirements-dev.txt
Tox is causing problems with ML GPU unit tests. Pin it until fixed.
=> Pin tox < 4.0.0

.github/CODEOWNERS
=> Update Code owners

.github/actions/install-main-dependencies/action.yml, .github/workflows/main.yml
=> Fix Aer build error in CI

.github/actions/install-main-dependencies/action.yml
=> Fix Aer cmake build error in CI

.github/actions/install-application/action.yml
=> Pin setuptools in CI

.github/workflows/main.yml, nature/asv.conf.json
=> Pin setuptools in Nature asv

.github/workflows/main.yml, nature/asv.conf.json
Reverts Qiskit/qiskit-app-benchmarks#76
Invalid Terra requirements specifier with "*" in Nature was removed. No need to pin setuptools anymore
=> Revert "Pin setuptools in Nature asv"
